# Multi-variable linear regression

hypothesis = H(x) = Wx + b

=> H(x1, x2, x3) => w1x1 + w2x2 + w3x3 + b

### Matrix multiplication(메트릭스 곱셈)

Hypothesis using matrix

(x1, x2, x3) * (w1  = (w1x1 + w2x2 + w3x3)
                w2
                w3)

### WX vs XW

- Lecture(theory) : H(x) = Wx + b
- Implementation(TensorFlow) : H(X) = XW

In [11]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

w1 = tf.Variable(tf.random.normal([1]), name='w1')
w2 = tf.Variable(tf.random.normal([1]), name='w2')
w3 = tf.Variable(tf.random.normal([1]), name='w3')
b = tf.Variable(tf.random.normal([1]), name='bias')

optimizer = tf.keras.optimizers.SGD(learning_rate=1e-5)

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = x1_data * w1 + x2_data * w2 + x3_data * w3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    grads = tape.gradient(cost, [w1, w2, w3, b])
    optimizer.apply_gradients(zip(grads, [w1, w2, w3, b]))

    if step % 500 == 0:
        print(f"Step: {step:4d} | Cost: {cost.numpy():.4f}")


        print(f"  [학습된 파라미터]")
        print(f"  w1: {w1.numpy()[0]:.3f}, w2: {w2.numpy()[0]:.3f}, w3: {w3.numpy()[0]:.3f}, b: {b.numpy()[0]:.3f}")


        print(f"  [성능 비교]")
        print(f"  실제값(Y): {y_data}")

        preds = [round(x, 1) for x in hypothesis.numpy()]
        print(f"  예측값(H): {preds}")
        print("-" * 60)



Step:    0 | Cost: 37797.8516
  [학습된 파라미터]
  w1: 0.282, w2: 1.775, w3: -1.298, b: 0.026
  [성능 비교]
  실제값(Y): [152.0, 185.0, 180.0, 196.0, 142.0]
  예측값(H): [np.float32(-10.6), np.float32(-29.4), np.float32(-20.0), np.float32(-26.5), np.float32(-22.6)]
------------------------------------------------------------
Step:  500 | Cost: 32.3903
  [학습된 파라미터]
  w1: 0.829, w2: 2.025, w3: -0.825, b: 0.031
  [성능 비교]
  실제값(Y): [152.0, 185.0, 180.0, 196.0, 142.0]
  예측값(H): [np.float32(160.7), np.float32(178.6), np.float32(183.9), np.float32(195.6), np.float32(136.5)]
------------------------------------------------------------
Step: 1000 | Cost: 25.1655
  [학습된 파라미터]
  w1: 0.937, w2: 1.875, w3: -0.783, b: 0.030
  [성능 비교]
  실제값(Y): [152.0, 185.0, 180.0, 196.0, 142.0]
  예측값(H): [np.float32(159.7), np.float32(179.3), np.float32(183.5), np.float32(195.4), np.float32(137.3)]
------------------------------------------------------------
Step: 1500 | Cost: 19.6456
  [학습된 파라미터]
  w1: 1.031, w2: 1.743, w3: -0.74

### Loading Data From File

In [19]:
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [192.]
 [196.]
 [142.]
 [101.]]


In [35]:
import tensorflow as tf
import numpy as np
import ast

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

w = tf.Variable(tf.random.normal([3,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

optimizer = tf.keras.optimizers.SGD(learning_rate=1e-5)

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(x_data, w) + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    grads = tape.gradient(cost, [w, b])
    optimizer.apply_gradients(zip(grads, [w, b]))

    if step % 100 == 0:
        print(f"Step: {step:4d} | Cost: {cost.numpy():.4f}")
print("--- 학습 완료! ---", )

while True:
    print("\n점수 데이터를 리스트 형태로 입력하세요. (종료하려면 q 입력)")
    print("예시 : [[73,80,75]] 또는 [[73,80,87],[93,88,93]]")

    user_input= input("입력 > ")

    if user_input == 'q':
        break

    try:
        my_scores = ast.literal_eval(user_input)

        my_tensor = tf.constant(my_scores, dtype=tf.float32)

        pred_result = tf.matmul(my_tensor, w) + b

        print("-" * 30)
        for i, res in enumerate(pred_result.numpy()):
            print(f"데이터 {i+1}번 {my_scores[i]}의 예상 점수: {res[0]:.2f}점")
        print("-" * 30)
    except ValueError:
        print("⚠ 형식이 잘못되었습니다. 괄호[]와 콤마, 숫자를 확인해주세요.")
    except Exception as e:
        print(f"⚠ 오류 발생: {e}")

Step:    0 | Cost: 86263.8984
Step:  100 | Cost: 30.2880
Step:  200 | Cost: 30.0832
Step:  300 | Cost: 29.8850
Step:  400 | Cost: 29.6930
Step:  500 | Cost: 29.5067
Step:  600 | Cost: 29.3261
Step:  700 | Cost: 29.1507
Step:  800 | Cost: 28.9800
Step:  900 | Cost: 28.8141
Step: 1000 | Cost: 28.6526
Step: 1100 | Cost: 28.4953
Step: 1200 | Cost: 28.3418
Step: 1300 | Cost: 28.1922
Step: 1400 | Cost: 28.0460
Step: 1500 | Cost: 27.9033
Step: 1600 | Cost: 27.7638
Step: 1700 | Cost: 27.6271
Step: 1800 | Cost: 27.4935
Step: 1900 | Cost: 27.3626
Step: 2000 | Cost: 27.2343
--- 학습 완료! ---

점수 데이터를 리스트 형태로 입력하세요. (종료하려면 q 입력)
예시 : [[73,80,75]] 또는 [[73,80,87],[93,88,93]]
------------------------------
데이터 1번 [75, 78, 80]의 예상 점수: 161.25점
------------------------------

점수 데이터를 리스트 형태로 입력하세요. (종료하려면 q 입력)
예시 : [[73,80,75]] 또는 [[73,80,87],[93,88,93]]
------------------------------
데이터 1번 [75, 78, 80]의 예상 점수: 161.25점
------------------------------

점수 데이터를 리스트 형태로 입력하세요. (종료하려면 q 입력)
예시 : [[73,80,75]] 

KeyboardInterrupt: Interrupted by user